# Use an official Node.js runtime as a parent image
version: 0.2

phases:
  build:
    commands:
      - name: Install dependencies
        command: npm install
      - name: Build Docker image
        command: docker build -t b950bbfb5430.dkr.ap-south-1.amazonaws.com/mynodeapp:latest .
      - name: Push Docker image to ECR
        command: docker push b950bbfb5430.dkr.ecr.ap-south-1.amazonaws.com/myapp:latest
